In [17]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [19]:
!pip install -q keras

In [20]:
import keras

In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [52]:
#importing the dataset
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/deep learning a-z/ann resource file/Churn_Modelling.csv')
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [53]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X = X[:,1:]

In [54]:
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


Splitting the dataset into the Training set and Test set


In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [56]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [57]:
#Initializing the ANN
ann = tf.keras.models.Sequential()

In [58]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [59]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [60]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [61]:
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [62]:
#Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 893us/step - loss: 0.7525 - accuracy: 0.5181
Epoch 2/100
250/250 [==============================] - 0s 859us/step - loss: 0.4909 - accuracy: 0.7946
Epoch 3/100
250/250 [==============================] - 0s 875us/step - loss: 0.4541 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 0s 878us/step - loss: 0.4343 - accuracy: 0.8004
Epoch 5/100
250/250 [==============================] - 0s 900us/step - loss: 0.4222 - accuracy: 0.8059
Epoch 6/100
250/250 [==============================] - 0s 925us/step - loss: 0.4128 - accuracy: 0.8124
Epoch 7/100
250/250 [==============================] - 0s 888us/step - loss: 0.4040 - accuracy: 0.8195
Epoch 8/100
250/250 [==============================] - 0s 921us/step - loss: 0.3949 - accuracy: 0.8281
Epoch 9/100
250/250 [==============================] - 0s 897us/step - loss: 0.3855 - accuracy: 0.8420
Epoch 10/100
250/250 [==============================] - 0s 924us/step - l

In [63]:
y_pred = ann.predict(X_test)
print(y_pred)

[[0.24356341]
 [0.30020133]
 [0.09333375]
 ...
 [0.19565961]
 [0.1415948 ]
 [0.21374199]]


In [64]:
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [65]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1507   88]
 [ 196  209]]
