In [17]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [19]:
!pip install -q keras

In [20]:
import keras

In [21]:
!pip install tensorflow

In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [27]:
#importing the dataset
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/deep learning a-z/ann/Churn_Modelling.csv')
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [29]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X = X[:,1:]

In [30]:
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


Splitting the dataset into the Training set and Test set


In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [33]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [36]:
#Initializing the ANN
ann = tf.keras.models.Sequential()

In [37]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [38]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [39]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [40]:
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [41]:
#Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 902us/step - loss: 0.5718 - accuracy: 0.7563
Epoch 2/100
250/250 [==============================] - 0s 902us/step - loss: 0.4676 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 941us/step - loss: 0.4393 - accuracy: 0.7959
Epoch 4/100
250/250 [==============================] - 0s 907us/step - loss: 0.4247 - accuracy: 0.7956
Epoch 5/100
250/250 [==============================] - 0s 960us/step - loss: 0.4096 - accuracy: 0.8064
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3916 - accuracy: 0.8307
Epoch 7/100
250/250 [==============================] - 0s 961us/step - loss: 0.3763 - accuracy: 0.8444
Epoch 8/100
250/250 [==============================] - 0s 919us/step - loss: 0.3659 - accuracy: 0.8482
Epoch 9/100
250/250 [==============================] - 0s 911us/step - loss: 0.3599 - accuracy: 0.8522
Epoch 10/100
250/250 [==============================] - 0s 884us/step - los

In [46]:
y_pred = ann.predict(X_test)
print(y_pred)

[[0.27190614]
 [0.35145575]
 [0.16028273]
 ...
 [0.12024865]
 [0.14624873]
 [0.22216144]]


In [47]:
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [49]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1493  102]
 [ 176  229]]


In [50]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

ValueError: ignored